-- S74-B Onayli bildirim puantaj etki adaylari migration
-- Additive migration; existing operational tables are not modified.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS onayli_bildirim_puantaj_etki_adaylari (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  genel_yonetici_bildirim_onayi_id INT UNSIGNED NOT NULL,
  aylik_bildirim_onayi_id INT UNSIGNED NOT NULL,
  gunluk_bildirim_id INT UNSIGNED NOT NULL,
  sube_id INT UNSIGNED NOT NULL,
  birim_amiri_user_id INT UNSIGNED NOT NULL,
  ay CHAR(7) NOT NULL,
  personel_id INT UNSIGNED NOT NULL,
  tarih DATE NOT NULL,
  bildirim_turu VARCHAR(32) NOT NULL,
  bildirim_alt_tur VARCHAR(64) NULL,
  bildirim_dakika INT UNSIGNED NULL,
  bildirim_aciklama TEXT NULL,
  bildirim_created_at TIMESTAMP NOT NULL,
  bildirim_updated_at TIMESTAMP NOT NULL,
  etki_turu VARCHAR(64) NOT NULL,
  etki_miktari INT UNSIGNED NULL,
  etki_birimi VARCHAR(16) NULL,
  state VARCHAR(32) NOT NULL,
  conflict_code VARCHAR(64) NULL,
  conflict_detail JSON NULL,
  resmi_surec_id INT UNSIGNED NULL,
  resmi_surec_turu VARCHAR(64) NULL,
  resmi_surec_alt_tur VARCHAR(64) NULL,
  ucretli_mi_snapshot TINYINT(1) NULL,
  mevcut_puantaj_id INT UNSIGNED NULL,
  source_priority VARCHAR(64) NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  source_snapshot JSON NULL,
  source_hash CHAR(64) NULL,
  projection_version VARCHAR(32) NULL DEFAULT 'S74_V1',
  PRIMARY KEY (id),
  UNIQUE KEY uniq_obpea_gybo_gunluk (genel_yonetici_bildirim_onayi_id, gunluk_bildirim_id),
  KEY idx_obpea_gybo (genel_yonetici_bildirim_onayi_id),
  KEY idx_obpea_personel_tarih (personel_id, tarih),
  KEY idx_obpea_sube_tarih (sube_id, tarih),
  KEY idx_obpea_state (state),
  KEY idx_obpea_conflict_code (conflict_code),
  CONSTRAINT fk_obpea_gybo FOREIGN KEY (genel_yonetici_bildirim_onayi_id) REFERENCES genel_yonetici_bildirim_onaylari (id),
  CONSTRAINT fk_obpea_aylik_onay FOREIGN KEY (aylik_bildirim_onayi_id) REFERENCES aylik_bildirim_onaylari (id),
  CONSTRAINT fk_obpea_gunluk_bildirim FOREIGN KEY (gunluk_bildirim_id) REFERENCES gunluk_bildirimler (id),
  CONSTRAINT fk_obpea_sube FOREIGN KEY (sube_id) REFERENCES subeler (id),
  CONSTRAINT fk_obpea_birim_amiri FOREIGN KEY (birim_amiri_user_id) REFERENCES users (id),
  CONSTRAINT fk_obpea_personel FOREIGN KEY (personel_id) REFERENCES personeller (id),
  CONSTRAINT fk_obpea_resmi_surec FOREIGN KEY (resmi_surec_id) REFERENCES surecler (id),
  CONSTRAINT fk_obpea_mevcut_puantaj FOREIGN KEY (mevcut_puantaj_id) REFERENCES gunluk_puantaj (id),
  CONSTRAINT fk_obpea_created_by FOREIGN KEY (created_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
