-- S77-D Maas hesaplama calistirma, aday, kalem ve audit tablolari
-- Additive; hesap sonucu overwrite edilmez; revision yeni satir uretir.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS maas_hesaplama_calistirmalari (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_id INT UNSIGNED NOT NULL,
  sube_id INT UNSIGNED NOT NULL,
  yil SMALLINT UNSIGNED NOT NULL,
  ay TINYINT UNSIGNED NOT NULL,
  revision_no INT UNSIGNED NOT NULL DEFAULT 1,
  parent_calistirma_id INT UNSIGNED NULL,
  state ENUM('HESAPLANDI', 'KISMI_HATA', 'IPTAL') NOT NULL DEFAULT 'HESAPLANDI',
  engine_version VARCHAR(48) NOT NULL,
  contract_version VARCHAR(48) NOT NULL DEFAULT 'S77D_PAYROLL_CANDIDATE_V1',
  snapshot_hash CHAR(64) NOT NULL,
  parameter_set_hash CHAR(64) NOT NULL,
  carryover_set_hash CHAR(64) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  source_hash CHAR(64) NOT NULL,
  result_hash CHAR(64) NOT NULL,
  calculation_input_hash CHAR(64) NOT NULL,
  personel_sayisi INT UNSIGNED NOT NULL DEFAULT 0,
  basarili_aday_sayisi INT UNSIGNED NOT NULL DEFAULT 0,
  hatali_aday_sayisi INT UNSIGNED NOT NULL DEFAULT 0,
  blocker_count INT UNSIGNED NOT NULL DEFAULT 0,
  warning_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  iptal_edildi_by INT UNSIGNED NULL,
  iptal_edildi_at TIMESTAMP NULL,
  iptal_nedeni VARCHAR(500) NULL,
  aktif_calistirma TINYINT(1) AS (
    CASE WHEN state = 'HESAPLANDI' THEN 1 ELSE NULL END
  ) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mhc_snapshot_revision (snapshot_id, revision_no),
  UNIQUE KEY uq_mhc_aktif (snapshot_id, aktif_calistirma),
  UNIQUE KEY uq_mhc_source_hash_aktif (snapshot_id, source_hash, aktif_calistirma),
  KEY idx_mhc_sube_donem (sube_id, yil, ay),
  KEY idx_mhc_input_hash (calculation_input_hash),
  KEY idx_mhc_result_hash (result_hash),
  CONSTRAINT fk_mhc_snapshot FOREIGN KEY (snapshot_id) REFERENCES maas_hesaplama_donem_snapshotlari (id),
  CONSTRAINT fk_mhc_sube FOREIGN KEY (sube_id) REFERENCES subeler (id),
  CONSTRAINT fk_mhc_parent FOREIGN KEY (parent_calistirma_id) REFERENCES maas_hesaplama_calistirmalari (id),
  CONSTRAINT fk_mhc_created_by FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_mhc_iptal_by FOREIGN KEY (iptal_edildi_by) REFERENCES users (id),
  CONSTRAINT chk_mhc_yil CHECK (yil BETWEEN 2000 AND 2100),
  CONSTRAINT chk_mhc_ay CHECK (ay BETWEEN 1 AND 12)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS maas_hesaplama_adaylari (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  calistirma_id INT UNSIGNED NOT NULL,
  personel_snapshot_id INT UNSIGNED NOT NULL,
  personel_id INT UNSIGNED NOT NULL,
  revision_no INT UNSIGNED NOT NULL DEFAULT 1,
  state ENUM('HESAPLANDI', 'HESAP_HATASI', 'IPTAL') NOT NULL DEFAULT 'HESAPLANDI',
  ucret_turu ENUM('BRUT', 'NET') NOT NULL,
  para_birimi CHAR(3) NOT NULL DEFAULT 'TRY',
  hedef_net_tutar DECIMAL(14,2) NULL,
  sozlesme_brut_tutar DECIMAL(14,2) NULL,
  hesaplanan_brut_tutar DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  sgk_matrahi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  gelir_vergisi_matrahi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  damga_vergisi_matrahi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  sgk_isci_primi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  issizlik_isci_primi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  gelir_vergisi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  damga_vergisi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  toplam_ek_odeme DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  toplam_kesinti DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  net_odenecek DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  sonraki_kumulatif_vergi_matrahi DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  input_hash CHAR(64) NOT NULL,
  result_hash CHAR(64) NOT NULL,
  engine_version VARCHAR(48) NOT NULL,
  carryover_json JSON NULL,
  solver_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mha_calistirma_personel (calistirma_id, personel_id),
  KEY idx_mha_personel_snapshot (personel_snapshot_id),
  KEY idx_mha_personel (personel_id),
  KEY idx_mha_result_hash (result_hash),
  CONSTRAINT fk_mha_calistirma FOREIGN KEY (calistirma_id) REFERENCES maas_hesaplama_calistirmalari (id),
  CONSTRAINT fk_mha_personel_snapshot FOREIGN KEY (personel_snapshot_id) REFERENCES maas_hesaplama_personel_snapshotlari (id),
  CONSTRAINT fk_mha_personel FOREIGN KEY (personel_id) REFERENCES personeller (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS maas_hesaplama_aday_kalemleri (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  aday_id INT UNSIGNED NOT NULL,
  sira_no INT UNSIGNED NOT NULL,
  kalem_grubu VARCHAR(32) NOT NULL,
  kalem_kodu VARCHAR(64) NOT NULL,
  yon ENUM('ARTI', 'EKSI', 'BILGI') NOT NULL,
  miktar DECIMAL(18,6) NULL,
  birim VARCHAR(16) NULL,
  oran DECIMAL(18,6) NULL,
  matrah DECIMAL(14,2) NULL,
  tutar DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  kaynak_turu VARCHAR(32) NULL,
  kaynak_id INT UNSIGNED NULL,
  aciklama VARCHAR(500) NULL,
  payload_json JSON NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mhak_aday_sira (aday_id, sira_no),
  KEY idx_mhak_kod (kalem_kodu),
  KEY idx_mhak_payload_hash (payload_hash),
  CONSTRAINT fk_mhak_aday FOREIGN KEY (aday_id) REFERENCES maas_hesaplama_adaylari (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS maas_hesaplama_auditleri (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  calistirma_id INT UNSIGNED NULL,
  snapshot_id INT UNSIGNED NULL,
  sube_id INT UNSIGNED NOT NULL,
  yil SMALLINT UNSIGNED NOT NULL,
  ay TINYINT UNSIGNED NOT NULL,
  aksiyon ENUM(
    'PREFLIGHT_BLOCKED',
    'CALCULATION_CREATE',
    'CALCULATION_IDEMPOTENT',
    'CALCULATION_CANCEL',
    'CALCULATION_REVISION',
    'CALCULATION_FAILED'
  ) NOT NULL,
  sonuc ENUM('BLOCKED', 'CREATED', 'EXISTING', 'CANCELLED', 'CONFLICT', 'FAILED') NOT NULL,
  actor_id INT UNSIGNED NOT NULL,
  actor_rol VARCHAR(40) NULL,
  request_hash CHAR(64) NOT NULL,
  calculation_input_hash CHAR(64) NULL,
  source_hash CHAR(64) NULL,
  result_hash CHAR(64) NULL,
  blocker_count INT UNSIGNED NOT NULL DEFAULT 0,
  warning_count INT UNSIGNED NOT NULL DEFAULT 0,
  snapshot_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mhaud_idempotency (sube_id, yil, ay, aksiyon, request_hash),
  KEY idx_mhaud_calistirma (calistirma_id),
  KEY idx_mhaud_snapshot (snapshot_id),
  KEY idx_mhaud_sube_donem (sube_id, yil, ay, created_at),
  CONSTRAINT fk_mhaud_calistirma FOREIGN KEY (calistirma_id) REFERENCES maas_hesaplama_calistirmalari (id),
  CONSTRAINT fk_mhaud_snapshot FOREIGN KEY (snapshot_id) REFERENCES maas_hesaplama_donem_snapshotlari (id),
  CONSTRAINT fk_mhaud_sube FOREIGN KEY (sube_id) REFERENCES subeler (id),
  CONSTRAINT fk_mhaud_actor FOREIGN KEY (actor_id) REFERENCES users (id),
  CONSTRAINT chk_mhaud_yil CHECK (yil BETWEEN 2000 AND 2100),
  CONSTRAINT chk_mhaud_ay CHECK (ay BETWEEN 1 AND 12)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
