-- Phase B: puantaj olay kararlari + disiplin vaka lifecycle (additive, idempotent).
-- MariaDB 10.6+ / PHP 7.4. No seed data.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS puantaj_olay_kararlari (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  personel_id INT UNSIGNED NOT NULL,
  tarih DATE NOT NULL,
  gunluk_puantaj_id INT UNSIGNED NULL,
  gunluk_bildirim_id INT UNSIGNED NULL,
  olay_turu ENUM('GEC_KALMA', 'ERKEN_CIKIS') NOT NULL,
  raw_dakika INT UNSIGNED NOT NULL,
  durumu_bildirdi_mi TINYINT(1) NULL,
  karar ENUM('BEKLIYOR', 'KESINTI_UYGULA', 'TOLERANS_UYGULA', 'OFFICIAL_PROCESS_REQUIRED') NOT NULL DEFAULT 'BEKLIYOR',
  karar_veren_user_id INT UNSIGNED NULL,
  karar_at TIMESTAMP NULL DEFAULT NULL,
  gerekce TEXT NULL,
  source_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pok_source_hash (source_hash),
  UNIQUE KEY uq_pok_personel_tarih_olay (personel_id, tarih, olay_turu),
  KEY idx_pok_personel_tarih (personel_id, tarih),
  KEY idx_pok_karar (karar),
  CONSTRAINT fk_pok_personel FOREIGN KEY (personel_id) REFERENCES personeller (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_pok_gunluk_puantaj FOREIGN KEY (gunluk_puantaj_id) REFERENCES gunluk_puantaj (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_pok_gunluk_bildirim FOREIGN KEY (gunluk_bildirim_id) REFERENCES gunluk_bildirimler (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_pok_karar_veren FOREIGN KEY (karar_veren_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT chk_pok_source_hash CHECK (source_hash REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS disiplin_vakalar (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  surec_id INT UNSIGNED NOT NULL,
  personel_id INT UNSIGNED NOT NULL,
  sube_id INT UNSIGNED NULL,
  tarih DATE NOT NULL,
  ay CHAR(7) NOT NULL,
  olay_turu VARCHAR(64) NOT NULL,
  lifecycle_state VARCHAR(32) NOT NULL DEFAULT 'INCELEME_ADAYI',
  raw_dakika INT UNSIGNED NULL,
  gunluk_puantaj_id INT UNSIGNED NULL,
  gunluk_bildirim_id INT UNSIGNED NULL,
  source_identity VARCHAR(160) NOT NULL,
  source_hash CHAR(64) NOT NULL,
  savunma_talep_tarihi DATE NULL,
  savunma_deadline_at DATETIME NULL,
  savunma_yer VARCHAR(255) NULL,
  savunma_konu VARCHAR(500) NULL,
  savunma_isteyen_user_id INT UNSIGNED NULL,
  savunma_belge_surec_id INT UNSIGNED NULL,
  savunma_received_at DATETIME NULL,
  nihai_karar VARCHAR(64) NULL,
  nihai_karar_gerekce TEXT NULL,
  nihai_karar_veren_user_id INT UNSIGNED NULL,
  nihai_karar_at TIMESTAMP NULL DEFAULT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_dv_surec (surec_id),
  UNIQUE KEY uq_dv_source_hash (source_hash),
  KEY idx_dv_personel_ay (personel_id, ay),
  KEY idx_dv_lifecycle (lifecycle_state),
  KEY idx_dv_sube_ay (sube_id, ay),
  CONSTRAINT fk_dv_surec FOREIGN KEY (surec_id) REFERENCES surecler (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_personel FOREIGN KEY (personel_id) REFERENCES personeller (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_sube FOREIGN KEY (sube_id) REFERENCES subeler (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_gunluk_puantaj FOREIGN KEY (gunluk_puantaj_id) REFERENCES gunluk_puantaj (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_gunluk_bildirim FOREIGN KEY (gunluk_bildirim_id) REFERENCES gunluk_bildirimler (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_savunma_isteyen FOREIGN KEY (savunma_isteyen_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_savunma_belge FOREIGN KEY (savunma_belge_surec_id) REFERENCES surecler (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_nihai_karar_veren FOREIGN KEY (nihai_karar_veren_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_dv_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT chk_dv_source_hash CHECK (source_hash REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS disiplin_vaka_auditleri (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  disiplin_vaka_id INT UNSIGNED NOT NULL,
  action VARCHAR(64) NOT NULL,
  from_state VARCHAR(32) NULL,
  to_state VARCHAR(32) NULL,
  actor_user_id INT UNSIGNED NULL,
  detail_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dva_vaka (disiplin_vaka_id),
  KEY idx_dva_created (created_at),
  CONSTRAINT fk_dva_vaka FOREIGN KEY (disiplin_vaka_id) REFERENCES disiplin_vakalar (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_dva_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
