export type PersonelAktifDurum = "AKTIF" | "PASIF";

export type Personel = {
  id: number;
  tc_kimlik_no: string;
  ad: string;
  soyad: string;
  aktif_durum: PersonelAktifDurum;
  sube_id?: number;
  telefon?: string;
  dogum_tarihi?: string;
  sicil_no?: string;
  dogum_yeri?: string;
  kan_grubu?: string;
  ise_giris_tarihi?: string;
  acil_durum_kisi?: string;
  acil_durum_telefon?: string;
  departman_id?: number;
  gorev_id?: number;
  personel_tipi_id?: number;
  bagli_amir_id?: number;
  sube_adi?: string;
  departman_adi?: string;
  gorev_adi?: string;
  personel_tipi_adi?: string;
  bagli_amir_adi?: string;
  hizmet_suresi?: string;
  toplam_izin_hakki?: number;
  kullanilan_izin?: number;
  kalan_izin?: number;
  sgk_donem?: string;
  sgk_prim_gun?: number;
  sgk_eksik_gun_sayisi?: number;
  sgk_ayin_takvim_gun_sayisi?: number;
  sgk_hesaplama_modu?: string;
  pasiflik_durumu_etiketi?: string | null;
};
